<div class="space-y-6">
    <div><p class="text-xs font-bold uppercase tracking-[0.2em] text-kejati-gold-dark">Sirkulasi</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Riwayat sirkulasi</h1><p class="mt-2 text-sm text-slate-500">Telusuri histori peminjaman berdasarkan anggota atau buku.</p></div>
    <div class="grid gap-3 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm md:grid-cols-3">
        <input aria-label="Cari nama peminjam" wire:model.live.debounce.300ms="search" placeholder="Cari nama peminjam…" class="rounded-xl border-stone-200 bg-stone-50 text-sm">
        <select aria-label="Filter anggota" wire:model.live="member_id" class="rounded-xl border-stone-200 bg-stone-50 text-sm"><option value="">Semua anggota</option>@foreach ($members as $member)<option value="{{ $member->id }}">{{ $member->nama }}</option>@endforeach</select>
        <select aria-label="Filter buku" wire:model.live="book_id" class="rounded-xl border-stone-200 bg-stone-50 text-sm"><option value="">Semua buku</option>@foreach ($books as $book)<option value="{{ $book->id }}">{{ $book->judul }}</option>@endforeach</select>
    </div>
    <div class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><caption class="sr-only">Riwayat sirkulasi perpustakaan</caption><thead class="bg-stone-50 text-xs uppercase text-slate-500"><tr><th class="px-6 py-4">Peminjam</th><th class="px-6 py-4">Buku</th><th class="px-6 py-4">Periode</th><th class="px-6 py-4">Status</th></tr></thead><tbody class="divide-y divide-stone-100">@forelse ($loans as $loan)<tr><td class="px-6 py-4"><p class="font-semibold">{{ $loan->nama_peminjam }}</p><p class="text-xs text-slate-500">{{ $loan->member?->nama ? 'Anggota: '.$loan->member->nama : 'Peminjam manual' }}</p></td><td class="px-6 py-4">{{ $loan->book?->judul ?? 'Buku dihapus' }}</td><td class="px-6 py-4">{{ $loan->tanggal_pinjam?->format('d M Y') }} — {{ $loan->tanggal_jatuh_tempo?->format('d M Y') }}</td><td class="px-6 py-4 font-semibold">{{ ucfirst($loan->current_status) }}</td></tr>@empty<tr><td colspan="4" class="px-6 py-12 text-center text-slate-500">Tidak ada riwayat.</td></tr>@endforelse</tbody></table></div><div class="border-t border-stone-100 px-6 py-4">{{ $loans->links() }}</div></div>
</div>
